#!/usr/bin/env bash
set -Ceu

if ! [ "$(which brew)" ]; then
    echo "Installing homebrew..."
    ruby <(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)
    while read LINE; do
      brew install ${LINE}
    done < $HOME/dotfiles/brewfile

    brew cask install alfred docker haskell-platform kitematic licecap sequel-pro chromedriver flux iterm2 leksah ngrok skitch cyberduck google-japanese-ime karabiner-elements libreoffice pg-commander xtrafinder
fi
